### ISSUE TITLE
3.3V and ground are reversed!!!!

### ISSUE THREAD

**Issue by TomKeddie** [flummer/supercon2019-protocartridge#1]
This is from this template.

![image](https://user-images.githubusercontent.com/4367175/68982484-05c0f800-07bc-11ea-9c85-3bc9b5603adb.png)

This is from sprite_tm

![image](https://user-images.githubusercontent.com/4367175/68982523-2ee18880-07bc-11ea-96f4-30dc4461fdb7.png)

**Comment by flummer** [comment]
It's not only the VCC and GND that is flipped, also the other 6 pins for SPI to the flash and the VBAT and +5V are flipped.

**Comment by flummer** [comment]
Both schematics and board files has now been updated to fix the polarity of the supply and the other mis configured pins on the cartridge connector.

**Comment by TomKeddie** [comment]
Thanks, you're quicker than I am!
